#Twitch auth information
TWITCH_CLIENT_ID =
TWITCH_SECRET =
OAUTH_TOKEN =

#twitter auth information
TWITTER_CONSUMER_KEY =
TWITTER_CONSUMER_SECRET =
TWITTER_ACCESS_TOKEN =
TWITTER_ACCESS_TOKEN_SECRET =
